// Uyanda.GUI.React.MicroService/react-app/src/components/Menu.tsx
import Title from "./Title";
import BeverageItem from "./beverageComponents/BeverageItem";
import { Beverage } from "../models/beverage.model";
import RemoveBeverageItem from "./beverageComponents/RemoveBeverageItem";
import AddBeverageItem from "./beverageComponents/AddBeverageItem";

interface Props {
  title: string;
  beverages: Beverage[];
  cart: Beverage[];
  addToCart(item: Beverage, cart: Beverage[]): void;
}

const Menu = ({ title = "boom fist", cart, addToCart, beverages }: Props) => {
  return (
    <>
      <div>
        <Title title={title} />
      </div>
      <div>
        <table className="table table-dark">
          <thead>
            <tr>
              <th scope="col">Item</th>
              <th scope="col">Type</th>
              <th scope="col">Size</th>
              <th scope="col">Price</th>
            </tr>
          </thead>
        </table>
        <ul className="list-group">
          {beverages &&
            beverages.map((item, index) => (
              <li
                key={item.id}
                className="list-group-item p-3 mb-2 bg-primary text-white"
              >
                <BeverageItem
                  beverageName={item.beverageName.name}
                  beverageType={item.beverageType.name}
                  beverageSize={item.beverageSize.name}
                  price={item.price.price}
                  count={item.count}
                />
                <div className="container">
                  <div className="row">
                    <div className="col-sm">
                      <RemoveBeverageItem />{" "}
                    </div>

                    <div className="col-sm">
                      <AddBeverageItem
                        addToCart={addToCart}
                        cart={cart}
                        item={item}
                      />
                    </div>
                  </div>
                </div>

                <div>
                  {/* <RemoveBeverageItem /> <p>{item.count}</p> <AddBeverageItem /> */}
                </div>
              </li>
            ))}
        </ul>
      </div>
    </>
  );
};

export default Menu;

// Uyanda.GUI.MicroService/src/app/menu/menu.component.ts
import { Component, OnInit } from '@angular/core';
import { Menu } from '../models/menu.model';
import { ApiCallService } from '../services/api-call.service';


@Component({
  selector: 'app-menu',
  templateUrl: './menu.component.html',
  styleUrls: ['./menu.component.css']
})
export class MenuComponent implements OnInit {

  constructor(private apiCall: ApiCallService) { }
  menu: Menu [] = [];
  private cart: [] = [];

  ngOnInit(): void {
    
    this.apiCall.menu().subscribe((element: any) => {
      this.menu = element

      console.log(this.menu);
      
    })
        
  }

  addToCart(element: Menu){

    console.log("add to cart method");
    
    console.log(element);
    
  }

}

<div class="container">
    <div class="row">
      <div class="col-sm">
       <ul>
        <p>Menu:</p>
        <li *ngFor="let item of menu">

            <div>
                <p>Beverage: {{item.beverageName.name}}</p>
                <p>Size: {{item.beverageSize.name}}</p>
                <p>Type: {{item.beverageType.name}} </p>
                <p>Price: R{{item.price}}</p>
            </div>

            <div>
              <button type="button" class="btn btn-primary" (click)="addToCart(item)">
                Add to Cart
              </button>
            </div>
        </li>
       </ul>
      </div>
    </div>
  </div>
